image: cirrusci/flutter:stable

stages:
  - build
  - deploy

build:repo:
  stage: build
  script:
    - git fetch origin
    - git fetch --tags
    - git --no-pager tag -l
    - export PATH="$PATH:$HOME/.pub-cache/bin"
    - flutter pub global activate repo_pub_server
    - cd hive
    - dart compile js lib/src/backend/js/web_worker/web_worker.dart -O4 -o lib/src/backend/js/web_worker/web_worker.dart.js
    - repo_pub_server https://famedly.gitlab.io/company/frontend/libraries/hive/ repo
    - mv repo ../
  artifacts:
    paths:
      - repo

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir public
    - mv repo/* public/
  dependencies:
    - build:repo
  artifacts:
    paths:
      - public
