include: package:lints/recommended.yaml


linter:
  rules:
    prefer_function_declarations_over_variables: false

analyzer:
  exclude:
    - lib/src/hive

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-arguments: 4
    maximum-nesting-level: 5
    source-lines-of-code: 50
    # This is still unstable, so handle with care
    maintainability-index: 40
  metrics-exclude:
    - test/**
  rules:
    #- newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    #- prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number:
        severity: style # too noisy otherwise atm
    - avoid-late-keyword:
        severity: style # too noisy otherwise atm
    - avoid-non-null-assertion:
        severity: style # too noisy otherwise atm
    - avoid-unused-parameters
    - binary-expression-operand-order
  anti-patterns:
    - long-method
    - long-parameter-list
