name: fluffybox
description: Easy to use but powerful storage for Flutter and web.
version: 0.4.3
homepage: https://famedly.com
repository: https://gitlab.com/famedly/company/frontend/libraries/fluffybox
issue_tracker: https://gitlab.com/famedly/company/frontend/libraries/fluffybox/issues

environment:
  sdk: '>=2.12.4 <3.0.0'

dependencies:
  crypto: ^3.0.0
  meta: ^1.3.0

dev_dependencies:
  dart_code_metrics: ^4.4.0
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
  file: any
